import Head from 'next/head'
import Header from '@components/header'
import Hero from '@components/hero'
import About from '@components/about'
import Experience from '@components/experience'
import Skills from '@components/skills'
import Projects from '@components/projects'
import Contact from '@components/contact'
import Link from 'next/link'
import { useTheme } from 'next-themes'
import { HiOutlineSun, HiMoon } from "react-icons/hi"

const Home = () => {

  const snap = 'snap-always snap-start'
  
  const HomeLink = () => {
    return (
      <div className='text-center flex justify-end p-8'>
        <Link className='hover:underline' href='#top'>Back to Top</Link>
      </div>
    )
  }

  const ModeButton = () => {
    const { theme, setTheme } = useTheme()

    return (
      <button onClick={():void => setTheme(theme === 'light' ? 'dark' : 'light')}
      className='px-4 py-2 text-[#e1ded7] bg-[#293744] rounded dark:text-[#293744]
      dark:bg-[#e1ded7] h-9 w-13'>
       { theme === 'light' ?
          <HiMoon className='h-5 w-5' /> :
          <HiOutlineSun className='h-5 w-5' />
        }
      </button>
    )
  }

  return (
    <>
      <Head>
        <title>Ant-Shell Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='snap-y snap-mandatory bg-[#e1ded7] text-[#293744]
      dark:bg-[#293744] dark:text-[#a89fa3] text-center w-screen overflow-auto select-none'>
        <div className={snap}>
          <Header />
          <div className='flex justify-end px-8 py-4'>
            <ModeButton />
          </div>
        </div>
        <div className={snap}>
          <Hero />
        </div>
        <div className={snap}>
          <About />
          <HomeLink/>
        </div>
        <div className={snap}>
          <Experience />
          <HomeLink/>
        </div>
        <div className={snap}>
          <Skills />
          <HomeLink/>
        </div>
        <div className={snap}>
          <Projects />
          <HomeLink/>
        </div>
        <div className={snap}>
          <Contact />
          <HomeLink/>
        </div>
      </main>
    </>
  )
}

export default Home
